server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein
spring:
  thymeleaf:
    cache: false
logging:
  path: .
  file: readinglist.log
  level:
    root: WARN
    org.springframework.security: DEBUG
